// Code generated by coz. DO NOT EDIT.
/**
 * Aside of the-component
 * @module the-aside
 */
'use strict'

import TheAside from './TheAside'
import TheAsideStyle from './TheAsideStyle'

export {
  TheAside,
  TheAsideStyle,
}

